import pandas as pd
import numpy as np
import yaml
from sklearn.preprocessing import StandardScaler
import os
import joblib
import logging
# Indicators are calculated manually since pandas-ta is failing in Python 3.11

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

class FeatureBuilder:
    def __init__(self, config_path="config.yaml"):
        with open(config_path, "r") as f:
            self.config = yaml.safe_load(f)
            
        self.target_col = self.config["data"]["target_col"]
        self.models_dir = self.config["paths"]["models_dir"]
        os.makedirs(self.models_dir, exist_ok=True)
        self.scaler_path = os.path.join(self.models_dir, "scaler.pkl")
        self.scaler = StandardScaler()
        # scaler for the target variable (closing price)
        self.target_scaler_path = os.path.join(self.models_dir, "target_scaler.pkl")
        self.target_scaler = StandardScaler()

    def create_features(self, df: pd.DataFrame, is_training: bool = True) -> pd.DataFrame:
        """Pipeline to create all features."""
        logger.info("Building features (Lags, Tech Indicators, Statistical)...")
        df = df.copy()
        
        df = self._add_lag_features(df)
        df = self._add_technical_indicators(df)
        df = self._add_statistical_features(df)
        
        # Add target column (next hour close)
        df['Target'] = df[self.target_col].shift(-1)
        
        # Drop NaN values generated by shifts and rolling windows
        df.dropna(inplace=True)
        
        logger.info(f"Features built successfully. Final shape: {df.shape}")
        return df

    def _add_lag_features(self, df: pd.DataFrame) -> pd.DataFrame:
        lags = [1, 2, 3, 6, 12, 24]
        for lag in lags:
            df[f'Close_Lag_{lag}'] = df['Close'].shift(lag)
            df[f'Volume_Lag_{lag}'] = df['Volume'].shift(lag)
        return df

    def _add_technical_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        # Manual indicator calculations to replace pandas-ta
        close = df['Close']
        
        # RSI 14
        delta = close.diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))
        
        # MACD (12, 26, 9)
        ema_12 = close.ewm(span=12, adjust=False).mean()
        ema_26 = close.ewm(span=26, adjust=False).mean()
        df['MACD'] = ema_12 - ema_26
        df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
        df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']
        
        # Bollinger Bands (20, 2)
        sma_20 = close.rolling(window=20).mean()
        std_20 = close.rolling(window=20).std()
        df['BBM'] = sma_20
        df['BBU'] = sma_20 + (std_20 * 2)
        df['BBL'] = sma_20 - (std_20 * 2)

        # EMAs and SMAs
        for period in [10, 20, 50]:
            df[f'EMA_{period}'] = close.ewm(span=period, adjust=False).mean()
            df[f'SMA_{period}'] = close.rolling(window=period).mean()
            
        # ATR 14
        high_low = df['High'] - df['Low']
        high_close = np.abs(df['High'] - close.shift())
        low_close = np.abs(df['Low'] - close.shift())
        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        df['ATR'] = tr.rolling(window=14).mean()
        
        return df

    def _add_statistical_features(self, df: pd.DataFrame) -> pd.DataFrame:
        df['rolling_mean_24'] = df['Close'].rolling(window=24).mean()
        df['rolling_volatility_24'] = df['Close'].rolling(window=24).std()
        df['momentum_24'] = df['Close'] - df['Close'].shift(24)
        df['log_returns'] = np.log(df['Close'] / df['Close'].shift(1))
        return df

    def scale_features(self, df: pd.DataFrame, feature_cols: list, is_training: bool = True) -> pd.DataFrame:
        """Normalize features before model training."""
        df_scaled = df.copy()
        
        if is_training:
            logger.info("Fitting and applying scaler to training data...")
            df_scaled[feature_cols] = self.scaler.fit_transform(df[feature_cols])
            joblib.dump(self.scaler, self.scaler_path)
            logger.info(f"Scaler saved to {self.scaler_path}")
        else:
            if os.path.exists(self.scaler_path):
                self.scaler = joblib.load(self.scaler_path)
                df_scaled[feature_cols] = self.scaler.transform(df[feature_cols])
            else:
                raise FileNotFoundError("Scaler file not found. Ensure models are trained before inference.")
                
        return df_scaled

    # ------------------------------------------------------------------
    # target-specific scaling utilities
    def scale_target(self, series: pd.Series, is_training: bool = True) -> pd.Series:
        """Scale the target (Close price) and persist scaler during training.
        Returns a pandas Series with the same index.
        """
        series_scaled = series.copy()
        arr = series.values.reshape(-1, 1)
        if is_training:
            logger.info("Fitting target scaler...")
            series_scaled = pd.Series(self.target_scaler.fit_transform(arr).flatten(), index=series.index)
            joblib.dump(self.target_scaler, self.target_scaler_path)
            logger.info(f"Target scaler saved to {self.target_scaler_path}")
        else:
            if os.path.exists(self.target_scaler_path):
                self.target_scaler = joblib.load(self.target_scaler_path)
                series_scaled = pd.Series(self.target_scaler.transform(arr).flatten(), index=series.index)
            else:
                raise FileNotFoundError("Target scaler file not found. Train models before inference.")
        return series_scaled

    def inverse_scale_target(self, values):
        """Inverse transform values that were scaled by the target scaler.
        Accepts a float, list, numpy array, or pandas Series and returns the
        corresponding unscaled numpy array (flattened).
        """
        if not hasattr(self, 'target_scaler') or not hasattr(self.target_scaler, "mean_"):
            if os.path.exists(self.target_scaler_path):
                self.target_scaler = joblib.load(self.target_scaler_path)
            else:
                raise FileNotFoundError("Target scaler not found. Ensure training has been run.")
        arr = np.array(values, dtype=float).reshape(-1, 1)
        inv = self.target_scaler.inverse_transform(arr)
        return inv.flatten()
